driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.4
  - name: ubuntu-13.04

suites:
  - name: default
    run_list:
      - recipe[df_ant::default]
      
    attributes:
